name: cogent3
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandoc
  - pip
  - pip:
    - sphinx>=1.6
    - nbsphinx
    - nbformat
    - nbconvert!=5.4
    - sphinxcontrib-bibtex
    - sphinx-gallery
    - sphinx_bootstrap_theme
